### ISSUE TITLE
Adding preserveModules: true within rollup config Outputs _virual/index.ts 

### ISSUE THREAD

**Issue by tsavo-vdb-knott** [darionco/rollup-typescript-webworkers#1]
Hey again 👋 

I have been working to optimize my rollup config on a large project and I have added preserveModules: true to my rollup config - when this is the case, it seems the worker plugin creates a _virtual folder with an index.ts file. Furthermore, it ends up replacing the import of the worker with something like ../_virtual/index.ts

Any thoughts on this?

Cheers, 
-Tsavo

**Comment by darionco** [comment]
hmmm, that's a scenario that I haven't looked at yet. I'll look at it some time this week and fix it/let you know.

**Comment by tsavo-vdb-knott** [comment]
Easy Ping on This :)

**Comment by darionco** [comment]
Seems to me like this is intended rollup behaviour:
https://github.com/rollup/rollup/pull/2511
